### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by spboyer** [bnb/good-first-issue#27]
via npx
```
$ npx good-first-issue node                                              
Unexpected token (
```

via npm global install
```good-first-issue node                                                 
/Users/shayneboyer/.npm-packages/lib/node_modules/good-first-issue/bin/good-first-issue.js:21
  .action(async (project, cmd) => {
                ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```

**Comment by spboyer** [comment]
node version issue. async functions not supported < 7.6

User/Dev error had n version set to 7 for some silly reason. Closing.
