### ISSUE TITLE
Tests failing for unknown reason

### ISSUE THREAD

**Issue by bnb** [bnb/good-first-issue#97]
Not sure why, but on my new machine the Jest tests are failing 🤔 

```
 FAIL  lib/search.spec.js
  ● should return filtered issues if there is only one page

    Cannot find module '@octokit/rest' from 'search.spec.js'

       7 |   jest.resetAllMocks()
       8 |   issues = jest.fn()
    >  9 |   jest.doMock('@octokit/rest', () => () => {
         |        ^
      10 |     return {
      11 |       search: {
      12 |         issues

      at Resolver.resolveModule (../../.nvm/versions/node/v10.14.2/lib/node_modules/jest/node_modules/jest-resolve/build/index.js:221:17)
      at Object.doMock (lib/search.spec.js:9:8)

  ● should return filtered issues if there is only one page

    TypeError: search is not a function

      64 |   })
      65 |
    > 66 |   return search({}).then(result => {
         |          ^
      67 |     expect(issues).toHaveBeenCalledTimes(1)
      68 |     expect(result).toEqual([
      69 |       {

      at Object.search (lib/search.spec.js:66:10)

  ● should return filtered issues if there is more than one page

    Cannot find module '@octokit/rest' from 'search.spec.js'

       7 |   jest.resetAllMocks()
       8 |   issues = jest.fn()
    >  9 |   jest.doMock('@octokit/rest', () => () => {
         |        ^
      10 |     return {
      11 |       search: {
      12 |         issues

      at Resolver.resolveModule (../../.nvm/versions/node/v10.14.2/lib/node_modules/jest/node_modules/jest-resolve/build/index.js:221:17)
      at Object.doMock (lib/search.spec.js:9:8)

  ● should return filtered issues if there is more than one page

    TypeError: search is not a function

      172 |   })
      173 |
    > 174 |   return search({}).then(result => {
          |          ^
      175 |     expect(issues).toHaveBeenCalledTimes(2)
      176 |     const searchParams = issues.mock.calls[1][0]
      177 |     expect(searchParams["page"]).toBeLessThanOrEqual(2)

      at Object.search (lib/search.spec.js:174:10)

  ● should return filtered issues if there are more than allowed pages

    Cannot find module '@octokit/rest' from 'search.spec.js'

       7 |   jest.resetAllMocks()
       8 |   issues = jest.fn()
    >  9 |   jest.doMock('@octokit/rest', () => () => {
         |        ^
      10 |     return {
      11 |       search: {
      12 |         issues

      at Resolver.resolveModule (../../.nvm/versions/node/v10.14.2/lib/node_modules/jest/node_modules/jest-resolve/build/index.js:221:17)
      at Object.doMock (lib/search.spec.js:9:8)

  ● should return filtered issues if there are more than allowed pages

    TypeError: search is not a function

      282 |   })
      283 |
    > 284 |   return search({}).then(result =>{
          |          ^
      285 |     expect(issues).toHaveBeenCalledTimes(2)
      286 |     const searchParams = issues.mock.calls[1][0]
      287 |     expect(searchParams["page"]).toBeLessThanOrEqual(34)

      at Object.search (lib/search.spec.js:284:10)

  ● should throw

    Cannot find module '@octokit/rest' from 'search.spec.js'

       7 |   jest.resetAllMocks()
       8 |   issues = jest.fn()
    >  9 |   jest.doMock('@octokit/rest', () => () => {
         |        ^
      10 |     return {
      11 |       search: {
      12 |         issues

      at Resolver.resolveModule (../../.nvm/versions/node/v10.14.2/lib/node_modules/jest/node_modules/jest-resolve/build/index.js:221:17)
      at Object.doMock (lib/search.spec.js:9:8)

  ● should throw

    TypeError: search is not a function

      305 |   const error = new Error('myError')
      306 |   issues.mockRejectedValue(error)
    > 307 |   await expect(search()).rejects.toEqual(error)
          |                ^
      308 | })
      309 |

      at Object.search (lib/search.spec.js:307:16)
```

**Comment by bnb** [comment]
I'm dumb and didn't `npm install` 😅
